export const CARD_SCRATCH_REQUEST = 'CARD_SCRATCH_REQUEST'
export const CARD_SCRATCH_SUCCESS = 'CARD_SCRATCH_SUCCESS'
export const CARD_SCRATCH_FAIL = 'CARD_SCRATCH_FAIL'
export const CARD_SCRATCH_RESET = 'CARD_SCRATCH_RESET'

export const CARD_LIST_SCRATCH_MY_REQUEST = 'CARD_LIST_SCRATCH_MY_REQUEST'
export const CARD_LIST_SCRATCH_MY_SUCCESS = 'CARD_LIST_SCRATCH_MY_SUCCESS'
export const CARD_LIST_SCRATCH_MY_FAIL = 'CARD_LIST_SCRATCH_MY_FAIL'
